version: '3.2'

networks:
  x-lab-test-task:
    external: true

volumes:
  x-lab-test-task-redis:
  x-lab-test-task-postgres:

services:
  x-lab-test-task-redis:
    image: bitnami/redis:6.2
    container_name: x-lab-test-task-redis
    environment:
      - REDIS_PASSWORD=x-lab-test-task-pass
    volumes:
      - x-lab-test-task-redis:/var/lib/redis/data
    restart: always
    networks:
      - x-lab-test-task

  x-lab-test-task-postgres:
    image: postgres:alpine
    container_name: x-lab-test-task-postgres
    environment:
      - POSTGRES_USER=x-lab-test-task
      - POSTGRES_DB=x-lab-test-task
      - POSTGRES_PASSWORD=x-lab-test-task-pass
    volumes:
      - x-lab-test-task-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - x-lab-test-task

  x-lab-test-task-web:
    image: &image x-lab-test-task-image
    build:
      context: .
    container_name: x-lab-test-task-web
    command: sh -c "alembic upgrade head && gunicorn application.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80"
    restart: always
    env_file:
      - .env
    ports:
      - 8010:80
    volumes:
      - .:/opt
    networks:
      - x-lab-test-task
