"""first

Revision ID: 277e551ef2f0
Revises: c4e74cef69db
Create Date: 2022-09-11 08:10:57.926409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277e551ef2f0'
down_revision = 'c4e74cef69db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdata')
    # ### end Alembic commands ###
